### ISSUE TITLE
"Install" command installs out-of-date Git files

### ISSUE THREAD

**Issue by tycrek** [MycroftAI/skill-homeassistant#30]
When using the voice command to install home assistant, it incorrectly installs the version with YAML settings. Doing a `git pull` in the homeassistant skills directory updates to the correct version, at which point the Skill can be configured at home.mycroft.ai.

Please fix the skill installation so it uses the JSON settings file instead of the broken YAML file. There is zero documentation for this, so hopefully this issue helps someone else.

**Comment by forslund** [comment]
The skill was updated just on Friday and hasn't been submitted to the Marketplace, we were pending a decision if the skill should be modified or if the backend should be fixed to handle the failing value. (both versions actually uses the yaml, just corrected syntax)

**Comment by forslund** [comment]
@tycrek The version in the marketplace has been updated. @krisgesling ended up reverting a couple of changes in the settingsmeta yaml file to match the old json (to hinder the backend from wiping the settings). Since you did an update to the previous half-finished state your settings may disappear from mycroft-home.)

**Comment by tycrek** [comment]
Ok, thanks for letting me know :)

Josh Moore
Software Developer
Visit my website <https://jmoore.dev/> or check out my GitHub <https://github.com/tycrek/>



Mar. 2, 2020, 7:26 a.m. by notifications@github.com:
